### ISSUE TITLE
No d.ts for Contents Plugin.

### ISSUE THREAD

**Issue by WeakKnight** [libondev/navmap#1]
![image](https://github.com/libondev/navmap/assets/12985760/a6e89f03-5314-4f74-981d-a90787eb7715)

**Comment by libondev** [comment]
Oh, thank you so much for noticing this

**Comment by libondev** [comment]
hi~, I have fixed this issue in the latest release of `0.3.1`, can you update the dependent version of `navmap` and try again?

**Comment by libondev** [comment]
Thank you for your valuable suggestions
